import re, os, string
def combineheader():
    toheader = re.compile(r'\n((?:\n[^\n]+)+)\n'
                          '\s*\/\*(\^|\<(?:[^>]|\>[^*]|\>\*[^/])*\>)\*\/')
    kandr = re.compile(r'\s*\{?\s*$')

    with open('chlwang.h', 'w') as outp:
        outp.write('/* This file is automatically generated. DO NOT EDIT! */\n\n')
        outp.write('#ifndef _' + 'chlwang_h' + '\n')
        outp.write('#define _' + 'chlwang_h' + '\n')
        for header in os.listdir("./"):
            if header.endswith(".h"):
                with open(header, 'r') as inp:
                    text = string.join(inp.readlines(),'')
                    for extract in toheader.findall(text):
                        if extract[1] == '^':
                            outp.write(extract[0]+'\n\n')
                            print extract[0]
                        else:
                            function = kandr.sub('', extract[0])
                            outp.write(function+'\n')
                            outp.write('/*'+extract[1]+'*/\n\n')

        outp.write('#endif \n')

combineheader()
