/* This file is automatically generated. DO NOT EDIT! */

#ifndef _utils_cuda_h
#define _utils_cuda_h


__device__ int getGlobalIdx_1D_1D();
/*< device get GlobalIdx with 1D grid 1D block >*/

#endif
