/* This file is automatically generated. DO NOT EDIT! */

#ifndef _fio_h
#define _fio_h


void read_float_1d(const char *file, float *a, int nx);
/*<write 1D float document>*/


void write_float_1d(const char *file, float *a, int nx);
/*<write 1D float document>*/


void read_float_2d(const char* file, float** a, int nx, int nz);
/*<read 2D float document>*/


void write_float_2d(const char* file, float** a, int nx, int nz);
/*<write 2D float document>*/


void read_float_3d(const char* file, float*** a, int nx, int ny, int nz);
/*<read 3D float document>*/


void write_float_3d(const char* file, float*** a, int nx, int ny, int nz);
/*<write 3D float document>*/


bool file_exists(char *filename);
/*<Checking if a file with filename exists.>*/


bool dir_exists(char *dirname);
/*<Checking if a directory with dirname exists.>*/


unsigned long count_lines_of_file(const char *file_patch);
/*<Returns number of lines in an ascii file.>*/


int getnlines(char *filename);
/*<Getting number of lines from file.>*/


int num_digit(const int n);
/*<Finding the number of digits in an integer using simple but efficient method.>*/

#endif
