/* This file is automatically generated. DO NOT EDIT! */

#ifndef _chlwang_cuda_h
#define _chlwang_cuda_h

void utils_print_title(const char *title);
/*<Printing out program title to terminal.>*/

#endif 
